-- phpMyAdmin SQL Dump
-- version 2.11.6
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Jul 31, 2018 at 06:10 PM
-- Server version: 5.0.51
-- PHP Version: 5.2.6

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `edufare`
--

-- --------------------------------------------------------

--
-- Table structure for table `course`
--

CREATE TABLE `course` (
  `course_id` int(5) NOT NULL auto_increment,
  `course_name` varchar(100) default NULL,
  `institute` varchar(50) default NULL,
  `cost` int(5) default NULL,
  `rating` float default NULL,
  `description` varchar(700) default NULL,
  `tag` varchar(25) default NULL,
  `start_date` date default NULL,
  `link` varchar(100) default NULL,
  `weekly_study` varchar(20) default NULL,
  `duration` int(5) default NULL,
  `category` varchar(50) default NULL,
  `stud_review` int(7) default NULL,
  `search` varchar(50) default NULL,
  `website` varchar(20) default NULL,
  `free` tinyint(1) default NULL,
  PRIMARY KEY  (`course_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=67 ;

--
-- Dumping data for table `course`
--

INSERT INTO `course` (`course_id`, `course_name`, `institute`, `cost`, `rating`, `description`, `tag`, `start_date`, `link`, `weekly_study`, `duration`, `category`, `stud_review`, `search`, `website`, `free`) VALUES
(1, 'Exploring Beethovenâ€™s Piano Sonatas', 'Curtis Institute of Music', NULL, NULL, 'Take your jazz music to the next level and learn how to play a jazz waltz, play in root position and more.', 'Course', '2018-08-13', 'https://www.coursera.org/learn/beethoven-piano-sonatas', NULL, 8, NULL, NULL, 'piano', 'coursera.com', NULL),
(2, 'Exploring Beethovenâ€™s Piano Sonatas Part 2', 'Curtis Institute of Music', NULL, NULL, 'Take your jazz music to the next level and learn how to play a jazz waltz, play in root position and more.', 'Course', '2018-08-20', 'https://www.coursera.org/learn/exploring-beethoven-piano-sonatas-2', NULL, 0, NULL, NULL, 'piano', 'coursera.com', NULL),
(3, 'Exploring Beethoven''s Piano Sonatas Part 3', 'Curtis Institute of Music', NULL, NULL, 'Take your jazz music to the next level and learn how to play a jazz waltz, play in root position and more.', 'Course', '2018-08-13', 'https://www.coursera.org/learn/exploring-beethoven-piano-sonatas-3', NULL, 0, NULL, NULL, 'piano', 'coursera.com', NULL),
(4, 'Robotics', 'University of Pennsylvania', NULL, NULL, 'Take your jazz music to the next level and learn how to play a jazz waltz, play in root position and more.', 'Specialization', '2018-08-13', 'https://www.coursera.org/specializations/robotics', NULL, 0, NULL, NULL, 'piano', 'coursera.com', NULL),
(5, 'Robotics: Aerial Robotics', 'University of Pennsylvania', NULL, NULL, 'Take your jazz music to the next level and learn how to play a jazz waltz, play in root position and more.', 'Course', '0000-00-00', 'https://www.coursera.org/learn/robotics-flight', NULL, 4, NULL, NULL, 'piano', 'coursera.com', NULL),
(6, 'Modern Robotics:  Mechanics, Planning, and Control', 'Northwestern University', NULL, NULL, 'Take your jazz music to the next level and learn how to play a jazz waltz, play in root position and more.', 'Specialization', '0000-00-00', 'https://www.coursera.org/specializations/modernrobotics', NULL, 4, NULL, NULL, 'piano', 'coursera.com', NULL),
(7, 'Modern Robotics, Course 1:  Foundations of Robot Motion', 'Northwestern University', NULL, NULL, 'Take your jazz music to the next level and learn how to play a jazz waltz, play in root position and more.', 'Course', '2018-08-06', 'https://www.coursera.org/learn/modernrobotics-course1', NULL, 435, NULL, NULL, 'piano', 'coursera.com', NULL),
(8, 'Robotics: Computational Motion Planning', 'University of Pennsylvania', NULL, NULL, 'Take your jazz music to the next level and learn how to play a jazz waltz, play in root position and more.', 'Course', '0000-00-00', 'https://www.coursera.org/learn/robotics-motion-planning', NULL, 3, NULL, NULL, 'piano', 'coursera.com', NULL),
(9, 'Controle de Sistemas no Plano-s', 'Instituto TecnolÃ³gico de AeronÃ¡utica', NULL, NULL, 'Take your jazz music to the next level and learn how to play a jazz waltz, play in root position and more.', 'Course', '2018-09-10', 'https://www.coursera.org/learn/controle-s', NULL, 0, NULL, NULL, 'piano', 'coursera.com', NULL),
(10, 'Strategic Management and Innovation', 'Copenhagen Business School', NULL, NULL, 'Take your jazz music to the next level and learn how to play a jazz waltz, play in root position and more.', 'Specialization', '2018-09-10', 'https://www.coursera.org/specializations/strategic-management', NULL, 0, NULL, NULL, 'piano', 'coursera.com', NULL),
(11, 'Strategic Management', 'Copenhagen Business School', NULL, NULL, 'Take your jazz music to the next level and learn how to play a jazz waltz, play in root position and more.', 'Course', '0000-00-00', 'https://www.coursera.org/learn/strategic-management', NULL, 424, NULL, NULL, 'piano', 'coursera.com', NULL),
(12, 'Fundamentos EstratÃ©gicos Empresariales', 'Universidad Nacional AutÃ³noma de MÃ©xico', NULL, NULL, 'Take your jazz music to the next level and learn how to play a jazz waltz, play in root position and more.', 'Specialization', '0000-00-00', 'https://www.coursera.org/specializations/fundamentos-empresariales', NULL, 424, NULL, NULL, 'piano', 'coursera.com', NULL),
(13, 'Strategic Planning and Execution', 'University of Virginia', NULL, NULL, 'Take your jazz music to the next level and learn how to play a jazz waltz, play in root position and more.', 'Course', '2018-08-06', 'https://www.coursera.org/learn/uva-darden-strategic-planning-execution', NULL, 425, NULL, NULL, 'piano', 'coursera.com', NULL),
(14, 'On Strategy : What Managers Can Learn from Philosophy - PART 1', 'CentraleSupÃ©lec', NULL, NULL, 'Take your jazz music to the next level and learn how to play a jazz waltz, play in root position and more.', 'Course', '2018-08-06', 'https://www.coursera.org/learn/management-philosophy', NULL, 0, NULL, NULL, 'piano', 'coursera.com', NULL),
(15, 'Strategy Implementation', 'Copenhagen Business School', NULL, NULL, 'Take your jazz music to the next level and learn how to play a jazz waltz, play in root position and more.', 'Course', '2018-08-06', 'https://www.coursera.org/learn/strategy-implementation', NULL, 24, NULL, NULL, 'piano', 'coursera.com', NULL),
(16, 'Orden y manejo del tiempo', 'Universidad Nacional AutÃ³noma de MÃ©xico', NULL, NULL, 'Take your jazz music to the next level and learn how to play a jazz waltz, play in root position and more.', 'Course', '2018-07-31', 'https://www.coursera.org/learn/orden', NULL, 0, NULL, NULL, 'piano', 'coursera.com', NULL),
(17, 'Strategy and Sustainability', 'IESE Business School', NULL, NULL, 'Take your jazz music to the next level and learn how to play a jazz waltz, play in root position and more.', 'Course', '0000-00-00', 'https://www.coursera.org/learn/strategy-sustainability', NULL, 23, NULL, NULL, 'piano', 'coursera.com', NULL),
(18, 'EstratÃ©gicos Empresariales Proyecto Final', 'Universidad Nacional AutÃ³noma de MÃ©xico', NULL, NULL, 'Take your jazz music to the next level and learn how to play a jazz waltz, play in root position and more.', 'Course', '2018-10-08', 'https://www.coursera.org/learn/estrategicos-empresariales-proyecto', NULL, 434, NULL, NULL, 'piano', 'coursera.com', NULL),
(19, 'La disrupciÃ³n del Blockchain', 'Universidad Austral', NULL, NULL, 'Take your jazz music to the next level and learn how to play a jazz waltz, play in root position and more.', 'Course', '2018-08-13', 'https://www.coursera.org/learn/blockchain-espanol', NULL, 54, NULL, NULL, 'piano', 'coursera.com', NULL),
(20, 'Los gobiernos locales como actores internacionales', 'Universidad Nacional AutÃ³noma de MÃ©xico', NULL, NULL, 'Take your jazz music to the next level and learn how to play a jazz waltz, play in root position and more.', 'Course', '2018-08-06', 'https://www.coursera.org/learn/gobiernos-locales', NULL, 423, NULL, NULL, 'piano', 'coursera.com', NULL),
(21, 'Exploring Beethovenâ€™s Piano Sonatas', 'Curtis Institute of Music', NULL, 4848, 'Take your jazz music to the next level and learn how to play a jazz waltz, play in root position and more.', 'Course', '2018-08-13', 'https://www.coursera.org/learn/beethoven-piano-sonatas', NULL, 8, NULL, 478, 'piano', 'coursera.com', NULL),
(22, 'Exploring Beethovenâ€™s Piano Sonatas Part 2', 'Curtis Institute of Music', NULL, 5050, 'Take your jazz music to the next level and learn how to play a jazz waltz, play in root position and more.', 'Course', '2018-08-20', 'https://www.coursera.org/learn/exploring-beethoven-piano-sonatas-2', NULL, 0, NULL, 65, 'piano', 'coursera.com', NULL),
(23, 'Exploring Beethoven''s Piano Sonatas Part 3', 'Curtis Institute of Music', NULL, 4949, 'Take your jazz music to the next level and learn how to play a jazz waltz, play in root position and more.', 'Course', '2018-08-13', 'https://www.coursera.org/learn/exploring-beethoven-piano-sonatas-3', NULL, 0, NULL, 41, 'piano', 'coursera.com', NULL),
(24, 'Robotics', 'University of Pennsylvania', NULL, 4949, 'Take your jazz music to the next level and learn how to play a jazz waltz, play in root position and more.', 'Specialization', '2018-08-13', 'https://www.coursera.org/specializations/robotics', NULL, 0, NULL, 41, 'piano', 'coursera.com', NULL),
(25, 'Robotics: Aerial Robotics', 'University of Pennsylvania', NULL, 4545, 'Take your jazz music to the next level and learn how to play a jazz waltz, play in root position and more.', 'Course', '0000-00-00', 'https://www.coursera.org/learn/robotics-flight', NULL, 4, NULL, 1, 'piano', 'coursera.com', NULL),
(26, 'Modern Robotics:  Mechanics, Planning, and Control', 'Northwestern University', NULL, 4545, 'Take your jazz music to the next level and learn how to play a jazz waltz, play in root position and more.', 'Specialization', '0000-00-00', 'https://www.coursera.org/specializations/modernrobotics', NULL, 4, NULL, 1, 'piano', 'coursera.com', NULL),
(27, 'Modern Robotics, Course 1:  Foundations of Robot Motion', 'Northwestern University', NULL, 4646, 'Take your jazz music to the next level and learn how to play a jazz waltz, play in root position and more.', 'Course', '2018-08-06', 'https://www.coursera.org/learn/modernrobotics-course1', NULL, 435, NULL, 29, 'piano', 'coursera.com', NULL),
(28, 'Robotics: Computational Motion Planning', 'University of Pennsylvania', NULL, 4242, 'Take your jazz music to the next level and learn how to play a jazz waltz, play in root position and more.', 'Course', '0000-00-00', 'https://www.coursera.org/learn/robotics-motion-planning', NULL, 3, NULL, 630, 'piano', 'coursera.com', NULL),
(29, 'Controle de Sistemas no Plano-s', 'Instituto TecnolÃ³gico de AeronÃ¡utica', NULL, 4747, 'Take your jazz music to the next level and learn how to play a jazz waltz, play in root position and more.', 'Course', '2018-09-10', 'https://www.coursera.org/learn/controle-s', NULL, 0, NULL, 51, 'piano', 'coursera.com', NULL),
(30, 'Strategic Management and Innovation', 'Copenhagen Business School', NULL, 4747, 'Take your jazz music to the next level and learn how to play a jazz waltz, play in root position and more.', 'Specialization', '2018-09-10', 'https://www.coursera.org/specializations/strategic-management', NULL, 0, NULL, 51, 'piano', 'coursera.com', NULL),
(31, 'Strategic Management', 'Copenhagen Business School', NULL, 4747, 'Take your jazz music to the next level and learn how to play a jazz waltz, play in root position and more.', 'Course', '0000-00-00', 'https://www.coursera.org/learn/strategic-management', NULL, 424, NULL, 1, 'piano', 'coursera.com', NULL),
(32, 'Fundamentos EstratÃ©gicos Empresariales', 'Universidad Nacional AutÃ³noma de MÃ©xico', NULL, 4747, 'Take your jazz music to the next level and learn how to play a jazz waltz, play in root position and more.', 'Specialization', '0000-00-00', 'https://www.coursera.org/specializations/fundamentos-empresariales', NULL, 424, NULL, 1, 'piano', 'coursera.com', NULL),
(33, 'Strategic Planning and Execution', 'University of Virginia', NULL, 4747, 'Take your jazz music to the next level and learn how to play a jazz waltz, play in root position and more.', 'Course', '2018-08-06', 'https://www.coursera.org/learn/uva-darden-strategic-planning-execution', NULL, 425, NULL, 209, 'piano', 'coursera.com', NULL),
(34, 'On Strategy : What Managers Can Learn from Philosophy - PART 1', 'CentraleSupÃ©lec', NULL, 4747, 'Take your jazz music to the next level and learn how to play a jazz waltz, play in root position and more.', 'Course', '2018-07-31', 'https://www.coursera.org/learn/management-philosophy', NULL, 0, NULL, 369, 'piano', 'coursera.com', NULL),
(35, 'Strategy Implementation', 'Copenhagen Business School', NULL, 4747, 'Take your jazz music to the next level and learn how to play a jazz waltz, play in root position and more.', 'Course', '2018-07-31', 'https://www.coursera.org/learn/strategy-implementation', NULL, 24, NULL, 501, 'piano', 'coursera.com', NULL),
(36, 'Orden y manejo del tiempo', 'Universidad Nacional AutÃ³noma de MÃ©xico', NULL, 4747, 'Take your jazz music to the next level and learn how to play a jazz waltz, play in root position and more.', 'Course', '2018-08-06', 'https://www.coursera.org/learn/orden', NULL, 0, NULL, 139, 'piano', 'coursera.com', NULL),
(37, 'Strategy and Sustainability', 'IESE Business School', NULL, 4545, 'Take your jazz music to the next level and learn how to play a jazz waltz, play in root position and more.', 'Course', '0000-00-00', 'https://www.coursera.org/learn/strategy-sustainability', NULL, 23, NULL, 83, 'piano', 'coursera.com', NULL),
(38, 'EstratÃ©gicos Empresariales Proyecto Final', 'Universidad Nacional AutÃ³noma de MÃ©xico', NULL, 0, 'Take your jazz music to the next level and learn how to play a jazz waltz, play in root position and more.', 'Course', '2018-10-08', 'https://www.coursera.org/learn/estrategicos-empresariales-proyecto', NULL, 434, NULL, 5, 'piano', 'coursera.com', NULL),
(39, 'La disrupciÃ³n del Blockchain', 'Universidad Austral', NULL, 4747, 'Take your jazz music to the next level and learn how to play a jazz waltz, play in root position and more.', 'Course', '2018-08-13', 'https://www.coursera.org/learn/blockchain-espanol', NULL, 54, NULL, 100, 'piano', 'coursera.com', NULL),
(40, 'Los gobiernos locales como actores internacionales', 'Universidad Nacional AutÃ³noma de MÃ©xico', NULL, 4747, 'Take your jazz music to the next level and learn how to play a jazz waltz, play in root position and more.', 'Course', '2018-08-06', 'https://www.coursera.org/learn/gobiernos-locales', NULL, 423, NULL, 173, 'piano', 'coursera.com', NULL),
(41, 'Java Programming and Software Engineering Fundamentals', 'Duke University', NULL, 4747, 'Take your jazz music to the next level and learn how to play a jazz waltz, play in root position and more.', 'Specialization', '2018-08-06', 'https://www.coursera.org/specializations/java-programming', NULL, 423, NULL, 173, 'java', 'coursera.com', NULL),
(42, 'Programming Foundations with JavaScript, HTML and CSS', 'Duke University', NULL, 4545, 'Take your jazz music to the next level and learn how to play a jazz waltz, play in root position and more.', 'Course', '2018-08-06', 'https://www.coursera.org/learn/duke-programming-web', NULL, 437, NULL, 4, 'java', 'coursera.com', NULL),
(43, 'HTML, CSS, and Javascript for Web Developers', 'Johns Hopkins University', NULL, 4949, 'Take your jazz music to the next level and learn how to play a jazz waltz, play in root position and more.', 'Course', '0000-00-00', 'https://www.coursera.org/learn/html-css-javascript-for-web-developers', NULL, 546, NULL, 3, 'java', 'coursera.com', NULL),
(44, 'Object Oriented Java Programming: Data Structures and Beyond', 'University of California San Diego', NULL, 4949, 'Take your jazz music to the next level and learn how to play a jazz waltz, play in root position and more.', 'Specialization', '0000-00-00', 'https://www.coursera.org/specializations/java-object-oriented', NULL, 546, NULL, 3, 'java', 'coursera.com', NULL),
(45, 'IntroducciÃ³n a Java', 'Universidad Nacional AutÃ³noma de MÃ©xico', NULL, 4545, 'Take your jazz music to the next level and learn how to play a jazz waltz, play in root position and more.', 'Course', '2018-08-20', 'https://www.coursera.org/learn/introduccion-java', NULL, 5, NULL, 14, 'java', 'coursera.com', NULL),
(46, 'Object Oriented Programming in Java', 'Duke University, University of California San Dieg', NULL, 4545, 'Take your jazz music to the next level and learn how to play a jazz waltz, play in root position and more.', 'Specialization', '2018-08-20', 'https://www.coursera.org/specializations/object-oriented-programming', NULL, 5, NULL, 14, 'java', 'coursera.com', NULL),
(47, 'Java Programming and Software Engineering Fundamentals', 'Duke University', NULL, 4545, 'Take your jazz music to the next level and learn how to play a jazz waltz, play in root position and more.', 'Specialization', '2018-08-20', 'https://www.coursera.org/specializations/java-programming', NULL, 5, NULL, 14, 'java', 'coursera.com', NULL),
(48, 'Programming Foundations with JavaScript, HTML and CSS', 'Duke University', NULL, 4545, 'Take your jazz music to the next level and learn how to play a jazz waltz, play in root position and more.', 'Course', '2018-08-06', 'https://www.coursera.org/learn/duke-programming-web', NULL, 437, NULL, 4, 'java', 'coursera.com', NULL),
(49, 'HTML, CSS, and Javascript for Web Developers', 'Johns Hopkins University', NULL, 4949, 'Take your jazz music to the next level and learn how to play a jazz waltz, play in root position and more.', 'Course', '0000-00-00', 'https://www.coursera.org/learn/html-css-javascript-for-web-developers', NULL, 546, NULL, 3, 'java', 'coursera.com', NULL),
(50, 'Object Oriented Java Programming: Data Structures and Beyond', 'University of California San Diego', NULL, 4949, 'Take your jazz music to the next level and learn how to play a jazz waltz, play in root position and more.', 'Specialization', '0000-00-00', 'https://www.coursera.org/specializations/java-object-oriented', NULL, 546, NULL, 3, 'java', 'coursera.com', NULL),
(51, 'IntroducciÃ³n a Java', 'Universidad Nacional AutÃ³noma de MÃ©xico', NULL, 4545, 'Take your jazz music to the next level and learn how to play a jazz waltz, play in root position and more.', 'Course', '2018-08-20', 'https://www.coursera.org/learn/introduccion-java', NULL, 5, NULL, 14, 'java', 'coursera.com', NULL),
(52, 'Object Oriented Programming in Java', 'Duke University, University of California San Dieg', NULL, 4545, 'Take your jazz music to the next level and learn how to play a jazz waltz, play in root position and more.', 'Specialization', '2018-08-20', 'https://www.coursera.org/specializations/object-oriented-programming', NULL, 5, NULL, 14, 'java', 'coursera.com', NULL),
(53, 'Java Programming: Solving Problems with Software', 'Duke University', NULL, 4646, 'Take your jazz music to the next level and learn how to play a jazz waltz, play in root position and more.', 'Course', '2018-08-06', 'https://www.coursera.org/learn/java-programming', NULL, 448, NULL, 1, 'java', 'coursera.com', NULL),
(54, 'Object Oriented Programming in Java', 'University of California San Diego', NULL, 4747, 'Take your jazz music to the next level and learn how to play a jazz waltz, play in root position and more.', 'Course', '0000-00-00', 'https://www.coursera.org/learn/object-oriented-java', NULL, 646, NULL, 2, 'java', 'coursera.com', NULL),
(55, 'Front-End JavaScript Frameworks: Angular', 'The Hong Kong University of Science and Technology', NULL, 4848, 'Take your jazz music to the next level and learn how to play a jazz waltz, play in root position and more.', 'Course', '2018-08-06', 'https://www.coursera.org/learn/angular', NULL, 468, NULL, 521, 'java', 'coursera.com', NULL),
(56, 'Java for Android', 'Vanderbilt University', NULL, 4545, 'Take your jazz music to the next level and learn how to play a jazz waltz, play in root position and more.', 'Course', '2018-08-07', 'https://www.coursera.org/learn/java-for-android', NULL, 456, NULL, 808, 'java', 'coursera.com', NULL),
(57, 'Ð Ð°Ð·Ñ€Ð°Ð±Ð¾Ñ‚ÐºÐ° Ð¸Ð½Ñ‚ÐµÑ€Ñ„ÐµÐ¹ÑÐ¾Ð²: Ð²Ñ‘Ñ€ÑÑ‚ÐºÐ° Ð¸ JavaScript', 'Yandex, Moscow Institute of Physics and Technology', NULL, 4545, 'Take your jazz music to the next level and learn how to play a jazz waltz, play in root position and more.', 'Specialization', '2018-08-07', 'https://www.coursera.org/specializations/razrabotka-interfeysov', NULL, 456, NULL, 808, 'java', 'coursera.com', NULL),
(58, 'Parallel, Concurrent, and Distributed Programming in Java', 'Rice University', NULL, 4545, 'Take your jazz music to the next level and learn how to play a jazz waltz, play in root position and more.', 'Specialization', '2018-08-07', 'https://www.coursera.org/specializations/pcdp', NULL, 456, NULL, 808, 'java', 'coursera.com', NULL),
(59, 'Responsive Website Basics: Code with HTML, CSS, and JavaScript', 'University of London, Goldsmiths, University of Lo', NULL, 4545, 'Take your jazz music to the next level and learn how to play a jazz waltz, play in root position and more.', 'Course', '0000-00-00', 'https://www.coursera.org/learn/website-coding', NULL, 424, NULL, 2, 'java', 'coursera.com', NULL),
(60, 'Interactivity with JavaScript', 'University of Michigan', NULL, 4646, 'Take your jazz music to the next level and learn how to play a jazz waltz, play in root position and more.', 'Course', '0000-00-00', 'https://www.coursera.org/learn/javascript', NULL, 0, NULL, 2, 'java', 'coursera.com', NULL),
(61, 'Java Programming: Arrays, Lists, and Structured Data', 'Duke University', NULL, 4747, 'Take your jazz music to the next level and learn how to play a jazz waltz, play in root position and more.', 'Course', '2018-08-06', 'https://www.coursera.org/learn/java-programming-arrays-lists-data', NULL, 448, NULL, 994, 'java', 'coursera.com', NULL),
(62, 'IntroducciÃ³n a la programaciÃ³n orientada a objetos en Java', 'Universidad de los Andes', NULL, 4848, 'Take your jazz music to the next level and learn how to play a jazz waltz, play in root position and more.', 'Course', '2018-08-13', 'https://www.coursera.org/learn/introduccion-programacion-java', NULL, 14512, NULL, 71, 'java', 'coursera.com', NULL),
(63, 'JavaScript, Ñ‡Ð°ÑÑ‚ÑŒ 1: Ð¾ÑÐ½Ð¾Ð²Ñ‹ Ð¸ Ñ„ÑƒÐ½ÐºÑ†Ð¸Ð¸', 'Yandex, Moscow Institute of Physics and Technology', NULL, 4545, 'Take your jazz music to the next level and learn how to play a jazz waltz, play in root position and more.', 'Course', '0000-00-00', 'https://www.coursera.org/learn/javascript-osnovy-i-funktsii', NULL, 0, NULL, 146, 'java', 'coursera.com', NULL),
(64, 'Parallel Programming in Java', 'Rice University', NULL, 4545, 'Take your jazz music to the next level and learn how to play a jazz waltz, play in root position and more.', 'Course', '0000-00-00', 'https://www.coursera.org/learn/parallel-programming-in-java', NULL, 48, NULL, 357, 'java', 'coursera.com', NULL),
(65, 'JavaScript, jQuery, and JSON', 'University of Michigan', NULL, 4747, 'Take your jazz music to the next level and learn how to play a jazz waltz, play in root position and more.', 'Course', '0000-00-00', 'https://www.coursera.org/learn/javascript-jquery-json', NULL, 10, NULL, 94, 'java', 'coursera.com', NULL),
(66, 'Initiation Ã  la programmation (en Java)', 'Ã‰cole Polytechnique FÃ©dÃ©rale de Lausanne', NULL, 4848, 'Take your jazz music to the next level and learn how to play a jazz waltz, play in root position and more.', 'Course', '0000-00-00', 'https://www.coursera.org/learn/initiation-programmation-java', NULL, 746, NULL, 182, 'java', 'coursera.com', NULL);
